version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_WEB_PORT}:8000"
    volumes:
      - ./src:/app/src
      - "storage:${APP_STORAGE_PATH}"
    env_file:
      - .env

volumes:
  storage:
